In [1]:
pip install pandas openpyxl

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.2.2)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.10/dist-packages (3.1.5)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.10/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [2]:
import pandas as pd
import numpy as np
import os

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

<h2>Converting different sheets from the main excel file into seperate excel files.</h2>

In [4]:
# Load the entire Excel file, with each sheet in a dictionary
file_path = '/content/drive/MyDrive/Datasets of WorldQuant University/Housing in mexico/010-housing-in-mexico.xlsx'
xls = pd.ExcelFile(file_path)

# Iterate through each sheet and save it as a new Excel file
for sheet_name in xls.sheet_names:
    # Load each sheet into a DataFrame
    df = pd.read_excel(xls, sheet_name=sheet_name)

    # Save each DataFrame to a new Excel file named after the sheet
    output_path = f"/content/drive/MyDrive/Datasets of WorldQuant University/Housing in mexico/{sheet_name}.xlsx"
    df.to_excel(output_path, index=False)

    print(f"Saved {sheet_name}.xlsx at {output_path}")

Saved brasil-real-estate-1.xlsx at /content/drive/MyDrive/Datasets of WorldQuant University/Housing in mexico/brasil-real-estate-1.xlsx
Saved brasil-real-estate-2.xlsx at /content/drive/MyDrive/Datasets of WorldQuant University/Housing in mexico/brasil-real-estate-2.xlsx
Saved mexico-real-estate-1.xlsx at /content/drive/MyDrive/Datasets of WorldQuant University/Housing in mexico/mexico-real-estate-1.xlsx
Saved mexico-real-estate-2.xlsx at /content/drive/MyDrive/Datasets of WorldQuant University/Housing in mexico/mexico-real-estate-2.xlsx
Saved mexico-real-estate-3.xlsx at /content/drive/MyDrive/Datasets of WorldQuant University/Housing in mexico/mexico-real-estate-3.xlsx

<h2>Converting different excel files that were created in the previous step from the main excel file into seperate csv files for further use.</h2>

In [5]:
# Define the directory containing the Excel files
directory_path = '/content/drive/MyDrive/Datasets of WorldQuant University/Housing in mexico/'

# List of specific Excel files to convert
excel_files_to_convert = [
    'brasil-real-estate-1.xlsx',
    'brasil-real-estate-2.xlsx',
    'mexico-real-estate-1.xlsx',
    'mexico-real-estate-2.xlsx',
    'mexico-real-estate-3.xlsx'
]

# Iterate through the list of specified Excel files
for filename in excel_files_to_convert:
    # Construct the full path to the Excel file
    file_path = os.path.join(directory_path, filename)

    # Check if the file exists in the directory
    if os.path.exists(file_path):
        # Load the Excel file into a DataFrame
        df = pd.read_excel(file_path)

        # Define the output CSV file path (same name as Excel but with .csv extension)
        csv_output_path = os.path.join(directory_path, f"{os.path.splitext(filename)[0]}.csv")

        # Save the DataFrame as a CSV file
        df.to_csv(csv_output_path, index=False)

        print(f"Converted {filename} to {csv_output_path}")
    else:
        print(f"File {filename} not found in the directory.")

Converted brasil-real-estate-1.xlsx to /content/drive/MyDrive/Datasets of WorldQuant University/Housing in mexico/brasil-real-estate-1.csv
Converted brasil-real-estate-2.xlsx to /content/drive/MyDrive/Datasets of WorldQuant University/Housing in mexico/brasil-real-estate-2.csv
Converted mexico-real-estate-1.xlsx to /content/drive/MyDrive/Datasets of WorldQuant University/Housing in mexico/mexico-real-estate-1.csv
Converted mexico-real-estate-2.xlsx to /content/drive/MyDrive/Datasets of WorldQuant University/Housing in mexico/mexico-real-estate-2.csv
Converted mexico-real-estate-3.xlsx to /content/drive/MyDrive/Datasets of WorldQuant University/Housing in mexico/mexico-real-estate-3.csv

In [6]:
df1=pd.read_csv('/content/drive/MyDrive/Datasets of WorldQuant University/Housing in mexico/brasil-real-estate-1.csv')

In [7]:
df2=pd.read_csv('/content/drive/MyDrive/Datasets of WorldQuant University/Housing in mexico/brasil-real-estate-2.csv')

In [8]:
df1.head()

,Unnamed: 0,property_type,place_with_parent_names,region,lat-lon,area_m2,price_usd
0,1,apartment,|Brasil|Alagoas|Maceió|,Northeast,"-9.6443051,-35.7088142",110,"$187,230.85"
1,2,apartment,|Brasil|Alagoas|Maceió|,Northeast,"-9.6430934,-35.70484",65,"$81,133.37"
2,3,house,|Brasil|Alagoas|Maceió|,Northeast,"-9.6227033,-35.7297953",211,"$154,465.45"
3,4,apartment,|Brasil|Alagoas|Maceió|,Northeast,"-9.622837,-35.719556",99,"$146,013.20"
4,5,apartment,|Brasil|Alagoas|Maceió|,Northeast,"-9.654955,-35.700227",55,"$101,416.71"

In [9]:
df2.head()

,Unnamed: 0,property_type,state,region,lat,lon,area_m2,price_brl
0,1,apartment,Pernambuco,Northeast,-8.134204,-34.906326,72.0,414222.98
1,2,apartment,Pernambuco,Northeast,-8.126664,-34.903924,136.0,848408.53
2,3,apartment,Pernambuco,Northeast,-8.125550,-34.907601,75.0,299438.28
3,4,apartment,Pernambuco,Northeast,-8.120249,-34.895920,187.0,848408.53
4,5,apartment,Pernambuco,Northeast,-8.142666,-34.906906,80.0,464129.36

In [10]:
df1.drop(columns=['Unnamed: 0'],inplace=True)

In [11]:
df2.drop(columns=['Unnamed: 0'],inplace=True)

In [12]:
df1.head()

,property_type,place_with_parent_names,region,lat-lon,area_m2,price_usd
0,apartment,|Brasil|Alagoas|Maceió|,Northeast,"-9.6443051,-35.7088142",110,"$187,230.85"
1,apartment,|Brasil|Alagoas|Maceió|,Northeast,"-9.6430934,-35.70484",65,"$81,133.37"
2,house,|Brasil|Alagoas|Maceió|,Northeast,"-9.6227033,-35.7297953",211,"$154,465.45"
3,apartment,|Brasil|Alagoas|Maceió|,Northeast,"-9.622837,-35.719556",99,"$146,013.20"
4,apartment,|Brasil|Alagoas|Maceió|,Northeast,"-9.654955,-35.700227",55,"$101,416.71"

In [13]:
df2.head()

,property_type,state,region,lat,lon,area_m2,price_brl
0,apartment,Pernambuco,Northeast,-8.134204,-34.906326,72.0,414222.98
1,apartment,Pernambuco,Northeast,-8.126664,-34.903924,136.0,848408.53
2,apartment,Pernambuco,Northeast,-8.125550,-34.907601,75.0,299438.28
3,apartment,Pernambuco,Northeast,-8.120249,-34.895920,187.0,848408.53
4,apartment,Pernambuco,Northeast,-8.142666,-34.906906,80.0,464129.36

In [14]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12834 entries, 0 to 12833
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   property_type            12834 non-null  object
 1   place_with_parent_names  12834 non-null  object
 2   region                   12834 non-null  object
 3   lat-lon                  11551 non-null  object
 4   area_m2                  12834 non-null  int64
 5   price_usd                12834 non-null  object
dtypes: int64(1), object(5)
memory usage: 601.7+ KB

In [15]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12833 entries, 0 to 12832
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   property_type  12833 non-null  object
 1   state          12833 non-null  object
 2   region         12833 non-null  object
 3   lat            12833 non-null  float64
 4   lon            12833 non-null  float64
 5   area_m2        11293 non-null  float64
 6   price_brl      12833 non-null  float64
dtypes: float64(4), object(3)
memory usage: 701.9+ KB

In [16]:
df1['place_with_parent_names'].head()

0    |Brasil|Alagoas|Maceió|
1    |Brasil|Alagoas|Maceió|
2    |Brasil|Alagoas|Maceió|
3    |Brasil|Alagoas|Maceió|
4    |Brasil|Alagoas|Maceió|
Name: place_with_parent_names, dtype: object

In [17]:
df2['state'].unique()

array(['Pernambuco', 'Piauí', 'Rio Grande do Norte', 'Rio Grande do Sul',
       'Rio de Janeiro', 'Rondônia', 'Santa Catarina', 'Sergipe',
       'São Paulo', 'Tocantins'], dtype=object)

In [18]:
def extract_second_element(location_string):
  """
  Extracts the second element from a pipe-delimited string.

  Args:
    location_string: A string with elements separated by pipes (|).

  Returns:
    The second element in the string, or None if it doesn't exist.
  """
  try:
    return location_string.split('|')[2]
  except IndexError:
    return None

# Apply the function to the 'place_with_parent_names' column
df1['state'] = df1['place_with_parent_names'].apply(extract_second_element)

# Print the unique values of the new column
print(df1['state'].unique())

['Alagoas' 'Amapá' 'Amazonas' 'Bahia' 'Ceará' 'Distrito Federal'
 'Espírito Santo' 'Goiás' 'Maranhão' 'Mato Grosso' 'Mato Grosso do Sul'
 'Minas Gerais' 'Paraná' 'Paraíba' 'Pará' 'Pernambuco']

In [19]:
df1.drop(columns=['place_with_parent_names'],inplace=True)

In [20]:
# Split the 'lat-lon' column into two separate columns
df1[['lat', 'lon']] = df1['lat-lon'].str.split(',', expand=True)

In [21]:
df1.drop(columns=['lat-lon'],inplace=True)

In [22]:
# Remove '$' and ',' from the 'price_usd' column
df1['price_usd'] = df1['price_usd'].astype(str).str.replace(r'[$,]', '', regex=True)

# Convert the 'price_usd' column to numeric
df1['price_usd'] = pd.to_numeric(df1['price_usd'])

In [23]:
# Convert 'area_m2' to float
df1['area_m2'] = df1['area_m2'].astype(float)
df1['lat'] = df1['lat'].astype(float)
df1['lon'] = df1['lon'].astype(float)

In [24]:
df1.dropna(inplace=True)

In [25]:
# Conversion rate
usd_to_brl_rate = 5.86873

# Calculate price_usd
df2['price_usd'] = df2['price_brl'] / usd_to_brl_rate

In [26]:
df2.drop(columns=['price_brl'],inplace=True)

In [27]:
df2.dropna(inplace=True)

In [28]:
df1.head()

  property_type     region  area_m2  price_usd    state       lat        lon
0     apartment  Northeast    110.0  187230.85  Alagoas -9.644305 -35.708814
1     apartment  Northeast     65.0   81133.37  Alagoas -9.643093 -35.704840
2         house  Northeast    211.0  154465.45  Alagoas -9.622703 -35.729795
3     apartment  Northeast     99.0  146013.20  Alagoas -9.622837 -35.719556
4     apartment  Northeast     55.0  101416.71  Alagoas -9.654955 -35.700227

In [29]:
df2.head()

,property_type,state,region,lat,lon,area_m2,price_usd
0,apartment,Pernambuco,Northeast,-8.134204,-34.906326,72.0,70581.365985
1,apartment,Pernambuco,Northeast,-8.126664,-34.903924,136.0,144564.246438
2,apartment,Pernambuco,Northeast,-8.125550,-34.907601,75.0,51022.671004
3,apartment,Pernambuco,Northeast,-8.120249,-34.895920,187.0,144564.246438
4,apartment,Pernambuco,Northeast,-8.142666,-34.906906,80.0,79085.144486

In [30]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11551 entries, 0 to 12833
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   property_type  11551 non-null  object
 1   region         11551 non-null  object
 2   area_m2        11551 non-null  float64
 3   price_usd      11551 non-null  float64
 4   state          11551 non-null  object
 5   lat            11551 non-null  float64
 6   lon            11551 non-null  float64
dtypes: float64(4), object(3)
memory usage: 721.9+ KB

In [31]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11293 entries, 0 to 12832
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   property_type  11293 non-null  object
 1   state          11293 non-null  object
 2   region         11293 non-null  object
 3   lat            11293 non-null  float64
 4   lon            11293 non-null  float64
 5   area_m2        11293 non-null  float64
 6   price_usd      11293 non-null  float64
dtypes: float64(4), object(3)
memory usage: 705.8+ KB

In [32]:
# Check for duplicate rows in the entire DataFrame
duplicate_rows = df1[df1.duplicated()]

# Display the duplicate rows, if any
if not duplicate_rows.empty:
    print("Duplicate rows:")
    print(duplicate_rows)
else:
    print("No duplicate rows found.")

Duplicate rows:
      property_type     region  area_m2  price_usd  state        lat  \
36            house  Northeast    202.0  154465.45  Bahia -12.852844
39            house  Northeast    202.0  154465.45  Bahia -12.852844
157       apartment  Northeast    115.0  115459.02  Bahia -12.992462
248       apartment  Northeast    128.0  152905.19  Bahia -12.985207
252       apartment  Northeast     71.0   81133.37  Bahia -12.852844
...             ...        ...      ...        ...    ...        ...
12683     apartment      North     79.0  115418.77   Pará  -1.418348
12684     apartment      North     65.0   90344.81   Pará  -1.418348
12688     apartment      North     56.0  141221.99   Pará  -1.441757
12720     apartment      North    118.0  202833.42   Pará  -1.456723
12730     apartment      North    138.0  234038.56   Pará  -1.431956

             lon
36    -38.327110
39    -38.327110
157   -38.444553
248   -38.456074
252   -38.327110
...          ...
12683 -48.479977
12684 -48.479977
12688 -48.473316
12720 -48.487934
12730 -48.455529

[976 rows x 7 columns]

In [33]:
# Check for duplicate rows in the entire DataFrame
duplicate_rows = df2[df2.duplicated()]

# Display the duplicate rows, if any
if not duplicate_rows.empty:
    print("Duplicate rows:")
    print(duplicate_rows)
else:
    print("No duplicate rows found.")

Duplicate rows:
      property_type                state     region        lat        lon  \
280       apartment           Pernambuco  Northeast  -8.040437 -34.883881
324       apartment           Pernambuco  Northeast  -8.036900 -34.884521
511       apartment  Rio Grande do Norte  Northeast  -5.777443 -35.200443
513       apartment  Rio Grande do Norte  Northeast  -5.777443 -35.200443
514       apartment  Rio Grande do Norte  Northeast  -5.777443 -35.200443
...             ...                  ...        ...        ...        ...
11906         house            São Paulo  Southeast -23.642342 -46.526363
12125     apartment            São Paulo  Southeast -23.618811 -46.737141
12224         house            São Paulo  Southeast -23.648643 -46.543930
12727     apartment            São Paulo  Southeast -23.518530 -46.665260
12743     apartment            São Paulo  Southeast -23.527826 -46.663685

       area_m2      price_usd
280       56.0   68030.233117
324       65.0   59356.373525
511       75.0   48262.956381
513       75.0   47742.131603
514       75.0   47568.525047
...        ...            ...
11906    147.0   98643.834356
12125    102.0  113100.258489
12224    127.0   93541.568619
12727    132.0  189232.571613
12743     58.0  104596.479988

[245 rows x 7 columns]

In [34]:
# Concatenate df2 to the end of df1
df = pd.concat([df1, df2], ignore_index=True)

In [35]:
df.head()

  property_type     region  area_m2  price_usd    state       lat        lon
0     apartment  Northeast    110.0  187230.85  Alagoas -9.644305 -35.708814
1     apartment  Northeast     65.0   81133.37  Alagoas -9.643093 -35.704840
2         house  Northeast    211.0  154465.45  Alagoas -9.622703 -35.729795
3     apartment  Northeast     99.0  146013.20  Alagoas -9.622837 -35.719556
4     apartment  Northeast     55.0  101416.71  Alagoas -9.654955 -35.700227

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22844 entries, 0 to 22843
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   property_type  22844 non-null  object
 1   region         22844 non-null  object
 2   area_m2        22844 non-null  float64
 3   price_usd      22844 non-null  float64
 4   state          22844 non-null  object
 5   lat            22844 non-null  float64
 6   lon            22844 non-null  float64
dtypes: float64(4), object(3)
memory usage: 1.2+ MB

In [37]:
# Check for duplicate rows in the entire DataFrame
duplicate_rows = df[df.duplicated()]

# Display the duplicate rows, if any
if not duplicate_rows.empty:
    print("Duplicate rows:")
    print(duplicate_rows)
else:
    print("No duplicate rows found.")

Duplicate rows:
      property_type     region  area_m2      price_usd      state        lat  \
31            house  Northeast    202.0  154465.450000      Bahia -12.852844
34            house  Northeast    202.0  154465.450000      Bahia -12.852844
135       apartment  Northeast    115.0  115459.020000      Bahia -12.992462
216       apartment  Northeast    128.0  152905.190000      Bahia -12.985207
219       apartment  Northeast     71.0   81133.370000      Bahia -12.852844
...             ...        ...      ...            ...        ...        ...
22029         house  Southeast    147.0   98643.834356  São Paulo -23.642342
22225     apartment  Southeast    102.0  113100.258489  São Paulo -23.618811
22315         house  Southeast    127.0   93541.568619  São Paulo -23.648643
22752     apartment  Southeast    132.0  189232.571613  São Paulo -23.518530
22766     apartment  Southeast     58.0  104596.479988  São Paulo -23.527826

             lon
31    -38.327110
34    -38.327110
135   -38.444553
216   -38.456074
219   -38.327110
...          ...
22029 -46.526363
22225 -46.737141
22315 -46.543930
22752 -46.665260
22766 -46.663685

[1221 rows x 7 columns]

In [38]:
# Remove duplicate rows, keeping only the first occurrence
df.drop_duplicates(keep='first', inplace=True)

In [39]:
df.head()

  property_type     region  area_m2  price_usd    state       lat        lon
0     apartment  Northeast    110.0  187230.85  Alagoas -9.644305 -35.708814
1     apartment  Northeast     65.0   81133.37  Alagoas -9.643093 -35.704840
2         house  Northeast    211.0  154465.45  Alagoas -9.622703 -35.729795
3     apartment  Northeast     99.0  146013.20  Alagoas -9.622837 -35.719556
4     apartment  Northeast     55.0  101416.71  Alagoas -9.654955 -35.700227

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 21623 entries, 0 to 22843
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   property_type  21623 non-null  object
 1   region         21623 non-null  object
 2   area_m2        21623 non-null  float64
 3   price_usd      21623 non-null  float64
 4   state          21623 non-null  object
 5   lat            21623 non-null  float64
 6   lon            21623 non-null  float64
dtypes: float64(4), object(3)
memory usage: 1.3+ MB

In [41]:
# Specify the output file path
excel_file_path = '/content/drive/MyDrive/Datasets of WorldQuant University/Housing in mexico/cleaned_brasil_dataset.xlsx'  # Replace with your desired file name and path

# Save the DataFrame to an Excel file
df.to_excel(excel_file_path, index=False)  # Set index=False to exclude row indices in the output

In [42]:
# Specify the output file path
csv_file_path = '/content/drive/MyDrive/Datasets of WorldQuant University/Housing in mexico/cleaned_brasil_dataset.csv'  # Replace with your desired file name and path

# Save the DataFrame to a CSV file
df.to_csv(csv_file_path, index=False)  # Set index=False to exclude row indices in the output